apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-pet
  labels:
    app: spring-pet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-pet
  template:
    metadata:
      labels:
        app: spring-pet
    spec:
      containers:
      - name: spring-pet
        image: bhanu3333/springpetclinic:1
        ports:
        - containerPort: 8080